swagger: '2.0'
info:
  version: '1.0'
  title: Api CCMS
  description: 'TODO: Add Description'
host: example.com
basePath: /
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /user/me:
    get:
      description: User Me
      summary: Me
      tags:
      - User
      operationId: UserMeGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /user/me
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Me
        x-testDescription: User Me
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /user:
    get:
      description: 'TODO: Add Description'
      summary: List
      tags:
      - User
      operationId: UserGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /user
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /auth/login:
    post:
      description: >
        Login
      summary: Login
      tags:
      - Auth
      operationId: AuthLoginPost
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /auth/login
          headers:
            Content-Type: application/x-www-form-urlencoded
          body: email=sty.adhi@gmail.com&password=1234
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Login
        x-testDescription: >
          Login
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /customerbms:
    get:
      description: 'TODO: Add Description'
      summary: List
      tags:
      - CustomerBMS
      operationId: CustomerbmsGet
      produces:
      - application/json
      parameters:
      - name: page
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /customerbms?page=1
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /customerbms/detail:
    get:
      description: 'TODO: Add Description'
      summary: Detail
      tags:
      - CustomerBMS
      operationId: CustomerbmsDetailGet
      produces:
      - application/json
      parameters:
      - name: id
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: includes
        in: query
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /customerbms/detail?id=1&includes=identities,kelurahan,kecamatan,kabupaten,privinsi,phone
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Detail
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /vehiclebms:
    get:
      description: 'TODO: Add Description'
      summary: List
      tags:
      - VehicleBms
      operationId: VehiclebmsGet
      produces:
      - application/json
      parameters:
      - name: customer_id
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /vehiclebms?customer_id=9831
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /vehiclebms/detail:
    get:
      description: 'TODO: Add Description'
      summary: Detail
      tags:
      - VehicleBms
      operationId: VehiclebmsDetailGet
      produces:
      - application/json
      parameters:
      - name: id
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /vehiclebms/detail?id=1
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Detail
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /contactplanner:
    get:
      description: 'TODO: Add Description'
      summary: List
      tags:
      - ContactPlanner
      operationId: ContactplannerGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /contactplanner
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /contactplanner/create:
    post:
      description: Create Contact Planner
      summary: Create
      tags:
      - ContactPlanner
      operationId: ContactplannerCreatePost
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: is_active
        in: formData
        required: true
        type: string
        description: active or not
      - name: name
        in: formData
        required: true
        type: string
        description: name of contact planner
      - name: code
        in: formData
        required: true
        type: string
        description: contact planner code (random string)
      - name: parameters
        in: formData
        required: true
        type: string
        description: parameters (json)
      - name: interval_type
        in: formData
        required: true
        type: string
        description: interval running (daily,weekly,monthly,custom)
      - name: activity_id
        in: formData
        required: true
        type: string
        description: activity_id | required
      - name: backdate
        in: formData
        required: true
        type: string
        description: backdate, tanggal query akan start berlaku.
      - name: week_days_interval
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /contactplanner/create
          headers:
            Content-Type: application/x-www-form-urlencoded
          body: is_active=1&name=SMS Reminder KPB 1&code=s3f34fd3221244ffbhrrsPP&parameters={"created_date":{"operator":"gt","value":"2018-08-27"}}&interval_type=daily&activity_id=0&backdate=2018-07-01&week_days_interval=sun,mon,thu
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create
        x-testDescription: Create Contact Planner
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /contactplanner/update:
    post:
      description: 'TODO: Add Description'
      summary: Update
      tags:
      - ContactPlanner
      operationId: ContactplannerUpdatePost
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: id
        in: formData
        required: true
        type: string
        description: ''
      - name: activity_id
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /contactplanner/update
          headers:
            Content-Type: application/x-www-form-urlencoded
          body: id=4&activity_id=1
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /activity/create:
    post:
      description: 'TODO: Add Description'
      summary: Create
      tags:
      - Activity
      operationId: ActivityCreatePost
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: activity_type
        in: formData
        required: true
        type: string
        description: type activity (sms,call,email)
      - name: is_enabled
        in: formData
        required: true
        type: string
        description: ''
      - name: sms_script
        in: formData
        required: true
        type: string
        description: isi dari sms kpb.
      - name: call_script
        in: formData
        required: true
        type: string
        description: ''
      - name: email_script
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /activity/create
          headers:
            Content-Type: application/x-www-form-urlencoded
          body: activity_type=sms&is_enabled=1&sms_script=hi {name}, ini adalah pemberitahuan service kpb anda&call_script=&email_script=
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /activity/detail:
    get:
      description: 'TODO: Add Description'
      summary: Detail
      tags:
      - Activity
      operationId: ActivityDetailGet
      produces:
      - application/json
      parameters:
      - name: id
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /activity/detail?id=1
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Detail
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /activity:
    get:
      description: 'TODO: Add Description'
      summary: List
      tags:
      - Activity
      operationId: ActivityGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /activity
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /branch:
    get:
      description: Get List BMS branch
      summary: List
      tags:
      - Branch
      operationId: BranchGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /branch
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: List
        x-testDescription: Get List BMS branch
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /commonbms/product:
    get:
      description: Endpoint for get all honda product from bms database.
      summary: Product
      tags:
      - Common
      operationId: CommonbmsProductGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /commonbms/product
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Product
        x-testDescription: Endpoint for get all honda product from bms database.
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
